mainsite/booking/urls.py
from django.urls import path
from . import views

# Contains paths for 6netic app
app_name = 'booking'

urlpatterns = [
    path('index', views.index, name='index'),
    path('home', views.home, name='home'),
    path('aeroports', views.aeroports, name='aeroports'),
    path('gares', views.gares, name='gares'),
    path('otherDestination', views.otherDestination, name='otherDestination'),
    path('displayJourney/<str:destination>/', views.displayJourney, name='displayJourney'),
    path('selectJourney', views.selectJourney, name='selectJourney'),
    path('recordJourney', views.recordJourney, name='recordJourney'),
    path('cancelJourney', views.cancelJourney, name='cancelJourney'),
]

mainsite/purbeurre/urls.py
from django.urls import path
from django.urls import include
from . import views


# Contains paths for purbeurre app
app_name = 'purbeurre'

urlpatterns = [
    #path('', views.homepage, name='homepage'),
    path('index', views.index, name='index'),
    path('legal', views.legal, name='legal'),
    path('search', views.search, name='search'),
    path('detail/<int:product_id>', views.detail, name='detail'),
    path('saveprd/', views.saveprd, name='saveprd'),
	path('showfavourites', views.showfavourites, name='showfavourites'),
    path('account', views.account, name='account'),
    path('register', views.register, name='register'),
	path('connect', views.connect, name='connect'),
	path('disconnect', views.disconnect, name='disconnect'),
	path('modifypassword', views.modifypassword, name='modifypassword'),
]

mainsite/purbeurre/models.py
# ./manage.py test purbeurre.tests.test_models -v 2
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser


class Category(models.Model):
    """ This class builds Category table """

    name = models.CharField(max_length=20, unique=True)

    class Meta:
        managed = True
        db_table = 'category'


class Product(models.Model):
    """ This class builds Product table """

    name = models.CharField(max_length=255, blank=True, null=True, unique=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    nutrition_grade = models.CharField(max_length=1, blank=True, null=True)
    barcode = models.CharField(max_length=255)
    url = models.CharField(max_length=255, blank=True, null=True)
    url_pic = models.CharField(max_length=255, blank=True, null=True)
    store = models.CharField(max_length=255, blank=True, null=True)
    prd_cat = models.ForeignKey(Category, models.DO_NOTHING, db_column='prd_cat')
    fat = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    saturated_fat = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    sugar = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    salt = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'product'


class Favourite(models.Model):
    """ This class builds Favourite table """

    former_barcode = models.CharField(max_length=80)
    favourite_barcode = models.CharField(max_length=80, unique=True)
    email_user = models.EmailField(max_length=150)

    class Meta:
        managed = True
        db_table = 'favourite'


class PbUserManager(BaseUserManager):
    """ Custom user model manager where email is the unique identifiers
        for authentication instead of usernames. """

    def create_user(self, email, password, **extra_fields):
        """ Create and save a User with the given email and password. """

        if not email:
            raise ValueError("Vous devez rentrer une adresse email.")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)  # rajouter username
        user.set_password(password)
        user.save()  # could also be user.save(using=self._db)
        return user


class PbUser(AbstractUser):
    """ This class redifines User model """

    username = models.CharField(
        verbose_name='Utilisateur',
        max_length=30,
    )
    email = models.EmailField(
        verbose_name='Adresse Email',
        max_length=255,
        unique=True,
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = PbUserManager()

    def __str__(self):
        return self.email

mainsite/purbeurre/forms.py
from django import forms
from django.contrib.auth.models import User


class MemberForm(forms.Form):
    """ This class creates a form to register a new member """

    username = forms.CharField(
        label="Nom d'utilisateur",
        min_length=2, max_length=30,
        widget=forms.TextInput,
        required=True,
    )
    email = forms.EmailField(
        label="Adresse Email",
        widget=forms.EmailInput,
        max_length=30,
        required=True
    )
    password = forms.CharField(
        label="Mot de passe",
        max_length=32,
        widget=forms.PasswordInput,
        required=True
    )


class ConnectionForm(forms.Form):
    """ This class creates a form to authenticate a user """

    email = forms.CharField(
        label="Adresse Email",
        widget=forms.TextInput
    )
    password = forms.CharField(
        label="Mot de passe",
        widget=forms.PasswordInput
    )
    redirection = forms.CharField(
        widget=forms.HiddenInput,
        required=False
    )


class ChangePasswordForm(forms.Form):
    """ This class creates a form to change user's password """

    old_password = forms.CharField(
        label="Entrez l'ancien mot de passe",
        widget=forms.PasswordInput,
        required=True
    )
    new_password1 = forms.CharField(
        label="Entrez le Nouveau mot de passe",
        max_length=32,
        widget=forms.PasswordInput,
        required=True
    )
    new_password2 = forms.CharField(
        label="Retapez le Nouveau mot de passe",
        max_length=32,
        widget=forms.PasswordInput,
        required=True
    )

mainsite/purbeurre/views.py
from django.http import HttpResponse
from .models import Category, Product, Favourite, PbUserManager, PbUser
from .forms import MemberForm, ConnectionForm, ChangePasswordForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.db import IntegrityError


def index(request):
    """ Homepage for purbeurre application """

    return render(request, 'purbeurre/index.html')


def legal(request):
    """ Redirects to legal mentions page """

    return render(request, 'purbeurre/legal.html')


def search(request):
    """ Finds a products the user is looking for """

    word = request.GET.get("search_word")
    # Retrieving the first product found
    try:
        search_prd = Product.objects.using('purbeurre').filter(name__icontains=word).first()
        search_prd_id = search_prd.id
        search_prd_nut = search_prd.nutrition_grade
        search_prd_cat = search_prd.prd_cat
        # Returns the first 6 products found
        best_prds = Product.objects.using('purbeurre').filter(prd_cat__exact=search_prd_cat). \
                        filter(nutrition_grade__lte=search_prd_nut). \
                        exclude(pk=search_prd_id)[:6]

        # Retrieves user email
        if request.user.is_authenticated:
            email = request.user.email
            favourites = Favourite.objects.using('purbeurre').all().filter(email_user=email)
            favourite_list = []
            for i in range(len(favourites)):
                new_code = favourites[i].favourite_barcode
                product = Product.objects.using('purbeurre').get(barcode=new_code).name
                favourite_list.append(product)

    except AttributeError:
        render(request, 'purbeurre/404.html')

    return render(request, 'purbeurre/result.html', locals())


def detail(request, product_id):
    """ Shows the detail of a specific food product """

    product = Product.objects.using('purbeurre').get(pk=product_id)
    context = {
        'product_name': product.name,
        'product_description': product.description,
        'product_nutrition_grade': product.nutrition_grade,
        'product_url': product.url,
        'product_url_pic': product.url_pic,
        'product_store': product.store,
        'product_fat': product.fat,
        'product_saturated_fat': product.saturated_fat,
        'product_sugar': product.sugar,
        'product_salt': product.salt,
    }
    return render(request, 'purbeurre/detail.html', context)


def saveprd(request):
    """ Saves a product into the database """

    former_barcode = request.GET.get("former_barcode")
    new_barcode = request.GET.get("new_barcode")
    email = request.user.email

    try:
        new_entry = Favourite.objects.using('purbeurre').create(
            former_barcode=former_barcode,
            favourite_barcode=new_barcode,
            email_user=email,
        )
        return HttpResponse(
            "<p align='center' style='color: green;'>Ce produit a bien été enregistré dans vos favoris</p>")
    except:
        return HttpResponse(
            "<p align='center' style='color: red;'>Ce produit a déjà été enregistré en base de données.</p>")


@login_required
def showfavourites(request):
    """ Shows all the registered products from a specific user """

    email = request.user.email
    favourites = Favourite.objects.using('purbeurre').all().filter(email_user=email)
    favourite_list = []
    for i in range(len(favourites)):
        new_code = favourites[i].favourite_barcode
        product = Product.objects.using('purbeurre').get(barcode=new_code)
        favourite_list.append(product)

    return render(request, 'purbeurre/favourite.html', locals())


def account(request):
    """ leads to member page """

    return render(request, 'purbeurre/account.html')


def register(request):
    """ This method is in charge of creating a new user in the database """

    form = MemberForm(request.POST or None)
    # Checking whether entered values from the formular are correct
    if form.is_valid():
        try:
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = PbUser.objects.create_user(
                username=username,
                email=email,
                password=password,
            )
            sending = 'ok'

        except IntegrityError:
            sending = 'nok'
        return render(request, 'purbeurre/register.html', locals())

    # if not in POST method then display the formular
    return render(request, 'purbeurre/register.html', locals())


def connect(request):
    """ This function connects a user to the system """

    # First access to connection form page
    if request.method == 'GET':
        redirection = request.GET.get('next')
    error = False

    if request.method == 'POST':
        form = ConnectionForm(request.POST)
        redirection = form["redirection"].value()

        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]

            user = authenticate(request, username=email, password=password)
            if user:
                login(request, user)

                if redirection != 'None':
                    return redirect(redirection)
            else:
                error = True
    else:
        form = ConnectionForm()

    return render(request, 'purbeurre/connection.html', locals())


def disconnect(request):
    """ Disconnects a user to the system """

    logout(request)
    return render(request, 'purbeurre/disconnection.html', locals())


def modifypassword(request):
    """ Modifies user's password """

    # This is a POST request so we need to process the form data
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            try:
                former_password = form.cleaned_data['old_password']
                new_password1 = form.cleaned_data['new_password1']
                new_password2 = form.cleaned_data['new_password2']

                if request.user.check_password(former_password):
                    if new_password1 == new_password2:
                        #print(request.user.email)
                        u = PbUser.objects.get(email=request.user.email)
                        u.set_password(new_password2)
                        u.save()

                        return render(request, 'purbeurre/passwordmodified.html')

                    else:
                        # Only former password is correct
                        resp = "onlyformer"

                else:
                    # Former password is false and new password is not the same in both fields
                    resp = "none"

            except:
                # Datas transmitted cannot be taken into account
                resp = "data_error"

            return render(request, 'purbeurre/modifypassword.html', locals())

    else:
        # First time the form is loaded
        form = ChangePasswordForm()

    return render(request, 'purbeurre/modifypassword.html', {'form': form})

mainsite/purbeurre/templates/purbeurre/account.html
{% extends "purbeurre/base.html" %}
{% load static %}
{% block content %}
    
    <section class="blackband">
    {% if user.is_authenticated %}
        <p class="nameprd">{{ user.username }}</p>
    {% else %}   
        <p class="nameprd">Espace membres</p>
    {% endif %}
    
    </section>

    <section class="bg-result">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    {% if user.is_authenticated %}
                        <p><h6 style="color: white;">Email : <i>{{ user }}</i></h6></p>
                        <p style="padding-top: 5rem;"><h5><a href="{% url 'purbeurre:modifypassword' %}">Modifier son mot de passe</a></h5></p>
                        <p style="margin-top: 6rem;"><h5><a href="{% url 'purbeurre:disconnect' %}">Se déconnecter</a></h5></p>
                    {% else %}
                        <p><h5><a href="{% url 'purbeurre:connect' %}">Se connecter</a></h5></p>
                        <p><h5><a href="{% url 'purbeurre:register' %}">Créer un compte</a></h5></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>    

{% endblock %}

mainsite/purbeurre/templates/purbeurre/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Trouver un aliment plus sain" />
        <meta name="author" content="" />
        <title>{% block title %}Pur Beurre{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
        <!-- Custom CSS-->       
        <link href="{% static 'purbeurre/css/styles.css' %}" rel="stylesheet" />
    </head>
    
    <body id="page-top">
        <!-- Navigation-->          
        <nav class="navbar navbar-expand-lg navbar-light navbar-fixed-top py-3" id="mainNav">
        <div class="container-fluid">                                 
            <a class="navbar-brand" href="{% url 'purbeurre:index' %}">
                <img id="logo" src="{% static 'purbeurre/assets/img/logo.png' %}" alt="Pur Beurre Logo">
                <span>Pur Beurre</span>
            </a>
{% block nav %}     


        <div class="right">
     {% block right %}
            <form action="{% url 'purbeurre:search' %}" method="get" accept-charset="utf-8">
                <input type="text" class="form-control" placeholder="Chercher" name="search_word">
            </form>
     {% endblock %}
        </div>


        <div id="sidebar">
     {% block sidebar %}
            <ul class="navbar-nav ml-auto my-2 my-lg-0">                   
            {% if user.is_authenticated %}
                <a href="{% url 'purbeurre:account' %}">
                <li class="nav-item">
                    <img class="headicons" src="{% static 'purbeurre/assets/img/account_icon.png' %}" alt="My Account"></li>
                </a>

                <a href="{% url 'purbeurre:showfavourites' %}">
                <li class="nav-item"><img class="headicons" src="{% static 'purbeurre/assets/img/foods_icon.png' %}" alt='My Account'>
                </li></a>
                <a href="{% url 'purbeurre:disconnect' %}">
                <li class="nav-item"><img class="headicons" src="{% static 'purbeurre/assets/img/disconnect_icon.png' %}" alt='My Account'></li></a>
            {% else %}
                <a href="{% url 'purbeurre:account' %}">
                <li class="nav-item">
                    <img class="headicons" src="{% static 'purbeurre/assets/img/account_icon.png' %}" alt="My Account"></li>
                </a>

            {% endif %}
            </ul>
    {% endblock %}
        </div>


{% endblock %}
        </div>
        </nav>           
          
        <section id="content">  
        {% block content %}
        {% endblock %}
        </section>

        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container">                
                <table align="center">
                    <tr>
                        <td><a href="{% url 'purbeurre:legal' %}" style="color: black;">Mentions légales</a></td>
                        <td style="padding-left: 3rem; padding-right: 3rem;"></td>
                        <td>Copyright © 2020 - Eric Bresler</td>
                    </tr>
                </table>

            </div>
        </footer>
        
        <!-- Custom JS script -->
        <script src="{% static 'purbeurre/assets/js/popup_saving.js' %}"></script>

    </body>
</html>


        

mainsite/purbeurre/templates/purbeurre/connection.html
{% extends "purbeurre/base.html" %}
{% load static %}
{% block content %}


    <section class="page-section bg-member" id="about">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <p><h1 class="text-white mt-0"><b>Page de connexion</b></h1><br /></p>
                        {% if error %}
                            <p align="center" style="color: red;">
                                <strong>Utilisateur inconnu ou mauvais de mot de passe.</strong>
                            </p>
                        {% endif %}                    
                        {% if user.is_authenticated %}
                            <p align="center" class="text-white">
                                <strong>Vous êtes connecté en tant que {{ user.username }} !</strong><br />
                            </p>
                        {% else %}                        
                           <div class="col-lg-8 text-center">
                               <div align="right">
                                   <form action="{% url 'purbeurre:connect' %}" method="post">
                                        {% csrf_token %}
                                        <div class="text-white">
                                            {{ form.as_p }}
                                        </div>
                                        <input type="submit" value="Connexion" />
                                        <input type="hidden" name="redirection" value="{{ redirection }}">
                                    </form>
                                </div>
                            </div>              
                        {% endif %}
                </div>
            </div>               
        </div>
    </section>       
{% endblock %}
<!--
    <section class="page-section bg-member" id="about">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <p><h1 class="text-white mt-0"><b>Page de connexion</b></h1><br /></p>
                    <p><h5><a href="{% url 'member:connect' %}">Se connecter</a></h5></p>
                    <p><h5><a href="{% url 'member:register' %}">Créer un compte</a></h5></p>
                </div>
            </div>
        </div>
    </section>
-->

mainsite/purbeurre/templates/purbeurre/favourite.html
{% extends "purbeurre/base.html" %}
{% load static %}
{% block content %}


        <section class="bg-result">
            <div class="container">
                <!-- <h3 class="text-center mt-0" style="color: white; padding-bottom: 3rem; font-weight: bold;">Mes Aliments favoris</h3><br /> -->
                <h3 class="text-center mt-0" id="replprod">Mes Aliments favoris</h3><br /> 
                <div class="row justify-content-center">
                {% for favourite in favourite_list %}
                    <div class="col-xs-6 text-center">
                        <p>
                            <a href="{% url 'purbeurre:detail' product_id=favourite.id %}">
                                <img class="img-responsive cube" src="{{ favourite.url_pic }}" alt="">
                            </a><br />
{% if favourite.nutrition_grade == 'a' %}                            
    <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/a.png' %}" alt="icone">{% endif %}
{% if favourite.nutrition_grade == 'b' %}                            
    <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/b.png' %}" alt="icone">{% endif %}
{% if favourite.nutrition_grade == 'c' %}                            
    <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/c.png' %}" alt="icone">{% endif %}
{% if favourite.nutrition_grade == 'd' %}                            
    <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/d.png' %}" alt="icone">{% endif %}
{% if favourite.nutrition_grade == 'e' %}                            
    <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/e.png' %}" alt="icone">{% endif %}

                            <span style="color: white;">{{ favourite.name }}<br /></span><br />
                                
                        </p>   
                            
                    </div>
                            
                {% endfor %}                        
                </div>
            </div>
        </section>
        
{% endblock %}

mainsite/purbeurre/templates/purbeurre/modifypassword.html
{% extends "purbeurre/base.html" %}
{% load static %}
{% block content %}


    <section class="blackband">
        <p class="nameprd">{{ user.username }}</p>
    </section>

    <section class="bg-result">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    {% if resp == 'onlyformer' %}
                        <p align="center" style="color: red;">
                            <strong>Le nouveau mot de passe n'est pas identique dans les deux champs.<br>
                            Veuillez recommencer.</strong>
                        </p>  
                    {% elif resp == 'none' %}
                        <p align="center" style="color: red;">
                            <strong>L'ancien mot de passe ne correspond pas.<br>
                            Veuillez recommencer.</strong>
                        </p> 
                    {% elif resp == 'data_error' %}
                        <p align="center" style="color: red;">
                            <strong>Il y a une erreur dans les données transmises.<br>
                            Veuillez recommencer.</strong>
                        </p> 
                    {% endif %}

                </div>
                <div class="col-sm-6">
                    <div align="right">
                        <form action="{% url 'purbeurre:modifypassword' %}" method="post">
                            {% csrf_token %}
                            <p>
                            <div class="text-white">
                                {{ form }}
                            </div>
                            </p>
                            <p></p><input type="submit" value="Envoyer">
                        </form>
                    </div>                    
                </div>
            </div>
        </div>
    </section>    

{% endblock %}

mainsite/purbeurre/templates/purbeurre/register.html
{% extends "purbeurre/base.html" %}
{% load static %}
{% block content %}


        <section class="page-section bg-member" id="about">            
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <p><h1 class="text-white mt-0"><b>Créer un compte</b></h1><br /></p>                  
                    {% if sending == 'ok' %}
                        <p align="center" class="text-white">
                            <strong>L'utilisateur {{ username }} a bien été enregistré. Merci.</strong>
                        </p>                    
                    {% else %}

                    {% if sending == 'nok' %}
                            <p align="center" style="color: red;">
                                <strong>Choisissez une autre adresse email car celle-ci est déjà enregistrée.</strong>
                            </p>
                    {% endif %}  

                        <div class="col-lg-8 text-center">
                            <div align="right">
                                <p>
                                <form action="{% url 'purbeurre:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="text-white">
                                        {{ form.as_p }}
                                    </div>
                                    <input type="submit" value="Enregistrer" />
                                </form>
                                </p>
                            </div>
                        </div>
                    {% endif %}
                </div>
              </div>
            </div>
        </section>
        
{% endblock %}

mainsite/purbeurre/templates/purbeurre/result.html
{% extends "purbeurre/base.html" %}
{% load static %}
{% block content %}

{% if search_prd %}
        <section class="blackband" style="background-image: url('{{ search_prd.url_pic }}');">
            <p class="nameprd">{{ search_prd.name }}</p>
        </section>
        <div id="popup-response" style="display: none;">
            <div id="popup"> 
                <p class="text-center w-50 mt-5"></p>
            </div>
        </div>

        <section class="bg-result">
            <div class="container">
                <h4 class="text-center mt-0" id="replprod">Vous pouvez remplacer cet aliment par :</h4><br /> 
                    <div class="row justify-content-center">                                          
                    {% for best_prd in best_prds %}
                        <div class="col-xs-6 text-center">
                            <p>
                                <a href="{% url 'purbeurre:detail' product_id=best_prd.id %}">
                                    <img class="img-responsive cube" src="{{ best_prd.url_pic }}" alt="">
                                </a><br />
    {% if best_prd.nutrition_grade == 'a' %}                            
        <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/a.png' %}" alt="icone">{% endif %}
    {% if best_prd.nutrition_grade == 'b' %}                            
        <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/b.png' %}" alt="icone">{% endif %}
    {% if best_prd.nutrition_grade == 'c' %}                            
        <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/c.png' %}" alt="icone">{% endif %}
    {% if best_prd.nutrition_grade == 'd' %}                            
        <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/d.png' %}" alt="icone">{% endif %}
    {% if best_prd.nutrition_grade == 'e' %}                            
        <img class="nutri" src="{% static 'purbeurre/assets/img/portfolio/thumbnails/e.png' %}" alt="icone">{% endif %}

                                <span style="color: white;">{{ best_prd.name }}</span><br />
                        {% if user.is_authenticated %}                                       
                                {% if best_prd.name in favourite_list %}
                                    <span style="color: blue; font-style: italic;">Enregistré</span>
                                {% else %}
                                    <a href="#" onclick="saving('{{best_prd.barcode}}');">
                                    <img class="save" src="{% static 'purbeurre/assets/img/save_icon.png' %}" alt='enregistrer'>
                                    <span>Sauvegarder</span>
                                    </a>
                                {% endif %}
                        {% else %}
                                <a href="{% url 'purbeurre:connect' %}">
                                <img class="save" src="{% static 'purbeurre/assets/img/save_icon.png' %}" alt='enregistrer'>
                                <span>Sauvegarder</span> 
                                </a>   
                        {% endif %}
                                
                            </p><br />
                        </div>                           
                    {% endfor %} 
                    </div>           
            </div>                                
        </section>       

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>        

    <script type="text/javascript" src="{% static 'purbeurre/assets/js/popup_saving.js' %}"></script>

{% else %}
    <section class="blackband">
    </section>

    <section class="bg-result">
        <div class="container">
            <h4 class="text-center mt-0">Aucune réponse trouvée. Merci de réessayer.</h4><br />
        </div>
    </section>

{% endif %}


{% endblock %}