mainsite/booking/urls.py
from django.urls import path
from . import views

# Contains paths for 6netic app
app_name = 'booking'

urlpatterns = [
    path('index', views.index, name='index'),
    path('home', views.home, name='home'),
    path('aeroports', views.aeroports, name='aeroports'),
    path('gares', views.gares, name='gares'),
    path('otherDestination', views.otherDestination, name='otherDestination'),
    path('displayJourney/<str:destination>/', views.displayJourney, name='displayJourney'),
    path('selectJourney', views.selectJourney, name='selectJourney'),
    path('recordJourney', views.recordJourney, name='recordJourney'),
    path('cancelJourney', views.cancelJourney, name='cancelJourney'),
]

mainsite/lorchidee/urls.py
from django.urls import path
from . import views


# Contains paths for lorchidee app
app_name = 'lorchidee'

urlpatterns = [
    path('index', views.index, name='index'),
    path('insertPlanning', views.insertPlanning, name='insertPlanning'),
    path('viewPlanning', views.viewPlanning, name='viewPlanning'),
    path('saveComment', views.saveComment, name='saveComment'),
]

mainsite/lorchidee/models.py
from django.db import models


class TimePlan(models.Model):
    """ Fields for TimePlan """

    jour = models.DateField()
    heure = models.CharField(max_length=5, blank=True, null=True)
    patient = models.CharField(max_length=65, blank=True, null=True)
    addrTel = models.CharField(max_length=255, blank=True, null=True)
    cotation = models.CharField(max_length=255, blank=True, null=True)
    assure = models.CharField(max_length=50, blank=True, null=True)
    honoraire = models.CharField(max_length=50, blank=True, null=True)
    finTraitement = models.CharField(max_length=50, blank=True, null=True)
    commentaires = models.CharField(max_length=255, blank=True, null=True)


    class Meta:
        managed = True
        db_table = 'timeplan'

mainsite/lorchidee/forms.py
from django import forms


class DateForm(forms.Form):
    """   """

    planningDate = forms.DateField(
        label='Date de la tournée:',
        widget=forms.TextInput(
            attrs={
                'label': "Trucy",
                'class': 'form-control',
                'type': 'date',
        })
    )

    file = forms.FileField(
        label='Choisir le fichier PDF:',
        widget=forms.FileInput(
            attrs={
                'class': 'form-control',
                'type': 'file',
        })
    )

mainsite/lorchidee/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from os import path
from tabula import convert_into
from pandas import read_csv
from . import forms
from . import models


def index(request):
    """ Main page of the application """

    return render(request, "lorchidee/index.html")


def insertPlanning(request):
    """ Insert a new schedule """

    if request.method == 'POST':
        try:
            myDate = request.POST.get('laDate')
            myFile = request.FILES.get('srcfile')
            currentPath = path.dirname(__file__)
            csvFolder = path.join(currentPath, "csv")
            csvFile = path.join(csvFolder, "output.csv")
            # Converting the pdf file into csv file
            convert_into(myFile, csvFile, output_format="csv", pages='all')
            # Retrieving csv file and converting it into dataframe set
            dataSet = read_csv(csvFile)
            data = dataSet.values[:, :]
            for line in data:
                col = []
                for column in line:
                    col.append(column)
                new_entry = models.TimePlan.objects.using('lorchidee').create(
                    jour=myDate,
                    heure=col[0],
                    patient=col[1],
                    addrTel=col[2],
                    cotation=col[3],
                    assure=col[4],
                    honoraire=col[5],
                    finTraitement=col[6],
                    commentaires=" ",
                )

            return render(request, "lorchidee/insertplan.html", {'insertOK': True})

        except:
            return render(request, "lorchidee/insertplan.html", {'insertNOK': True})

    form = forms.DateForm()
    return render(request, "lorchidee/insertplan.html", locals())


def viewPlanning(request):
    """ View for schedule """

    if request.method == 'POST':
        try:
            day = request.POST.get("laDate")
            daysWork = models.TimePlan.objects.using('lorchidee').filter(jour=day).order_by('id')
            if daysWork:
                return render(request, "lorchidee/viewplan.html", {'daysWork': daysWork})
            else:
                return render(request, "lorchidee/viewplan.html", {'daysEmpty': True})
        except:
            pass

    return render(request, "lorchidee/viewplan.html", {'data': 'first'})


def saveComment(request):
    """ Saving the note """

    if request.method == 'POST':
        try:
            note = request.POST.get('note')
            number = request.POST.get('number')
            entry = models.TimePlan.objects.using('lorchidee').get(pk=number)
            entry.commentaires = note
            entry.save()
        except:
            return HttpResponse("This note has not been saved")

    return HttpResponse("This entry has been correctly saved to the database")

mainsite/lorchidee/templates/lorchidee/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>L'Orchidee</title>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Bootstrap CSS File -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link href="{% static 'lorchidee/css/styles.css' %}" rel="stylesheet" />

</head>
<body id="page-top">

 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'lorchidee:index' %}">L'Orchidee</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Other</a>
        </li> -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Planning</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'lorchidee:insertPlanning' %}">Insertion</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'lorchidee:viewPlanning' %}">Visualisation</a></li>
          </ul>
        </li>

      </ul>

    </div>
  </div>
 </nav>

 <div id="wrapper">
{% block wrapper %}

{% endblock %}
 </div>

 <footer class="footer py-4">
   <div class="container">
     <table align="center">
       <tr>
         <td>Eric Bresler | www.6netic.eu</td>
       </tr>
     </table>
   </div>
 </footer>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


</body>
</html>

mainsite/lorchidee/templates/lorchidee/index.html
{% extends "lorchidee/base.html" %}

{% load static %}

{% block wrapper %}

    <section class="page-section" id="services">
        <div class="container">
            <div class="text-center">
                <!--<h2 class="section-heading text-uppercase">Services</h2>-->
                <br /><br />
                <h3 class="section-subheading text-muted">Page d'Accueil</h3>
                <br /><br />
         <p>Ce projet consiste à récupérer sous format PDF un planning créé par une application
            tierce.</p>
         <p>A partir de là, il est enregistré en BDD et l'utilisateur(trice) a la possibilité de
            le consulter en y insérant un commentaire sur chaque ligne.</p>

            </div>
            <div class="row text-center">


            </div>
        </div>
    </section>




{% endblock %}

mainsite/lorchidee/templates/lorchidee/insertplan.html
{% extends "lorchidee/base.html" %}

{% load static %}

{% block wrapper %}

    <section class="page-section" id="services">
      <div class="container">
        <div class="text-center">
          <!--<h2 class="section-heading text-uppercase">Services</h2>-->
          <br /><br />
          <h3 class="section-subheading text-muted">Insertion du Planning</h3>
          <br /><br /><br /><br />

          <div id="insertForm">
            <form action="{% url 'lorchidee:insertPlanning' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p><label for="laDate">Entrez la date de la tournée : </label>
                <input type="date" name="laDate" id="laDate"></p>
                <p><label for="srcfile">Import du fichier PDF : </label>
                <input type="file" name="srcfile" id="srcfile" accept="application/pdf"></p>
                <p><input type="submit" value="Envoyer"></p>
              </form>
          </div>
          <div id="confirmInsert">
          </div>
        </div>
      </div>
    </section>


{% if insertOK %}
  <script src="{% static 'lorchidee/js/insertPop.js' %}"></script>
{% elif insertNOK %}
  <script src="{% static 'lorchidee/js/insertPopErr.js' %}"></script>
{% endif %}

{% endblock %}

mainsite/lorchidee/templates/lorchidee/viewplan.html
{% extends "lorchidee/base.html" %}

{% load static %}

{% block wrapper %}

  <section class="page-section" id="services">
    <div class="container">
      <div class="text-center">
        <!--<h2 class="section-heading text-uppercase">Services</h2>-->
        <br /><br />
        <h3 class="section-subheading text-muted">Visualisation du Planning</h3>
        <br /><br /><br /><br />
   {% if data %}
     <form action="{% url 'lorchidee:viewPlanning' %}" method="post">
         {% csrf_token %}
        <p><label for="laDate">Entrez la date de la tournée : </label>
        <input type="date" name="laDate" id="laDate"></p>
        <p><input type="submit" value="Envoyer"></p>
     </form>
   {% endif %}
   {% if daysWork %}
      <table class="styled-table">
                <thead>
                  <tr>
                    <th>Heure</th>
                    <th>Patient</th>
                    <th>Adresse, Tél</th>
                    <th>Cotation, détail séance</th>
                    <th>Dû assuré</th>
                    <th>Honoraire</th>
                    <th>Fin de traitement</th>
                    <th>Commentaires</th>
                    <th></th>
                 </tr>
               </thead>
               <tbody>
           {% for one in daysWork %}
                  <tr>
                    <td>{{ one.heure }}</td>
                    <td>{{ one.patient }}</td>
                    <td>{{ one.addrTel }}</td>
                    <td>{{ one.cotation }}</td>
                    <td>{{ one.assure }}</td>
                    <td>{{ one.honoraire }}</td>
                    <td>{{ one.finTraitement }}</td>
                    <td id="noteclass{{ forloop.counter }}">{{ one.commentaires }}</td>
                    <td id="bout{{ forloop.counter }}">
                      <button type="button" class="btn btn-outline-success"
                        onclick="zone('noteclass{{ forloop.counter }}','bout{{ forloop.counter }}', '{{ one.id }}');">
                          Modifier
                      </button>
                    </td>
                  </tr>
           {% endfor %}
              </tbody>
     </table>

   {% elif daysEmpty %}
      <div style="color:blue;">Il n'y a aucun planning enregistré pour cette date.</div>
   {% endif %}
      </div>
    </div>
  </section>


<script type="text/javascript" src="{% static 'lorchidee/js/modifplanning.js' %}"></script>

{% endblock %}