mainsite/booking/urls.py
from django.urls import path
from . import views

# Contains paths for 6netic app
app_name = 'booking'

urlpatterns = [
    path('index', views.index, name='index'),
    path('home', views.home, name='home'),
    path('aeroports', views.aeroports, name='aeroports'),
    path('gares', views.gares, name='gares'),
    path('otherDestination', views.otherDestination, name='otherDestination'),
    path('displayJourney/<str:destination>/', views.displayJourney, name='displayJourney'),
    path('selectJourney', views.selectJourney, name='selectJourney'),
    path('recordJourney', views.recordJourney, name='recordJourney'),
    path('cancelJourney', views.cancelJourney, name='cancelJourney'),
]

mainsite/cinetic/urls.py
from django.urls import path
from . import views

# Contains paths for 6netic app
app_name = 'cinetic'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    #path('services', views.services, name='services'),
    path('projets', views.projets, name='projets'),
    path('contact', views.contact, name='contact'),
]

mainsite/lorchidee/urls.py
from django.urls import path
from . import views


# Contains paths for lorchidee app
app_name = 'lorchidee'

urlpatterns = [
    path('index', views.index, name='index'),
    path('insertPlanning', views.insertPlanning, name='insertPlanning'),
    path('viewPlanning', views.viewPlanning, name='viewPlanning'),
    path('saveComment', views.saveComment, name='saveComment'),
]

mainsite/purbeurre/urls.py
from django.urls import path
from django.urls import include
from . import views


# Contains paths for purbeurre app
app_name = 'purbeurre'

urlpatterns = [
    #path('', views.homepage, name='homepage'),
    path('index', views.index, name='index'),
    path('legal', views.legal, name='legal'),
    path('search', views.search, name='search'),
    path('detail/<int:product_id>', views.detail, name='detail'),
    path('saveprd/', views.saveprd, name='saveprd'),
	path('showfavourites', views.showfavourites, name='showfavourites'),
    path('account', views.account, name='account'),
    path('register', views.register, name='register'),
	path('connect', views.connect, name='connect'),
	path('disconnect', views.disconnect, name='disconnect'),
	path('modifypassword', views.modifypassword, name='modifypassword'),
]

mainsite/cinetic/models.py
from django.db import models

# Create your models here.

mainsite/cinetic/views.py
from django.shortcuts import render


def homepage(request):
    """ Homepage of the application """

    home = True
    return render(request, 'cinetic/index.html', locals())

'''
def services(request):
    """ Page Services of the application """

    services = True
    return render(request, 'cinetic/services.html', locals())
'''

def projets(request):
    """ Page Projects of the application """

    projets = True
    return render(request, 'cinetic/projets.html', locals())


def contact(request):
    """ Page Contact of the application """

    contact = True
    return render(request, 'cinetic/contact.html', locals())

mainsite/cinetic/templates/cinetic/contact.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block section %}

    <section id="contact" class="section-bg wow fadeInUp">
      <div class="container">

        <div class="section-header">
          <h3>{% translate "Me Contacter" %}</h3>
          <p> </p>
        </div>

        <div class="row contact-info">

          <div class="col-md-4">
            <div class="contact-address">
              <i class="ion-ios-location-outline"></i>
              <h3>{% translate "Adresse" %}</h3>
              <address>Région Parisienne, France</address>
            </div>
          </div>

          <div class="col-md-4">
            <div class="contact-phone">
              <i class="ion-ios-telephone-outline"></i>
              <h3>{% translate "Téléphone" %}</h3>
              <p><a href="#"></a></p>
            </div>
          </div>

          <div class="col-md-4">
            <div class="contact-email">
              <i class="ion-ios-email-outline"></i>
              <h3>{% translate "Email" %}</h3>
              <p><a href="mailto:ebresler@live.fr">ebresler@live.fr</a></p>
            </div>
          </div>

        </div>
        <br /><br /><br /><br /><br /><br />
        <!--<div class="form">
          <div id="sendmessage">Your message has been sent. Thank you!</div>
          <div id="errormessage"></div>
          <form action="" method="post" role="form" class="contactForm">
            <div class="form-row">
              <div class="form-group col-md-6">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-6">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                <div class="validation"></div>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
              <div class="validation"></div>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
              <div class="validation"></div>
            </div>
            <div class="text-center"><button type="submit">Send Message</button></div>
          </form>
        </div>-->

      </div>
    </section><!-- #contact -->

{% endblock %}  

mainsite/cinetic/templates/cinetic/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block section %}

  <section id="intro">
    <div class="intro-container">
      <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">

        <ol class="carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <!--<div class="carousel-item">
            <div class="carousel-background"><img src="{% static 'cinetic/assets/img/intro-carousel/1.jpg' %}" alt="">
          </div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Titre à trouver</h2>
                <p>
                  C'est parti ! Un nouveau livre, plus qu'une page s'ouvre. <br />
                  Un tournant pris et je me lance dans cette palpitante aventure programmatique.  
                  C'est mon site naissant qui grandira avec le temps.<br />
                  Mes projets sont d'abord présentés sur cette plateforme.<br />
                  Puis certainement, j'évoluerai vers la proposition de prestations.
                </p>
                <a href="#featured-services" class="btn-get-started scrollto">Get Started</a>
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="{% static 'cinetic/assets/img/intro-carousel/2.jpg' %}" alt="">
            </div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>At vero eos et accusamus</h2>
                <p>Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut.</p>
                <a href="#featured-services" class="btn-get-started scrollto">Get Started</a>
              </div>
            </div>
          </div>-->

          <div class="carousel-item active">
            <div class="carousel-background"><img src="{% static 'cinetic/assets/img/intro-carousel/3.jpg' %}" alt="">
            </div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>{% translate "Bienvenue sur 6netic.eu" %}</h2>
                <p>
                  {% translate "Ce site personnel a pour but de m'offir une visibilité sur le Web." %}<br />
                  {% translate "Passioné par le développement, j'y présente des projets réalisés en Python." %}<br />
                  {% translate "Son contenu n'est pas très fourni mais il a pour vocation de grossir avec le temps..." %}
                </p>
                <!--<a href="#featured-services" class="btn-get-started scrollto">Get Started</a>-->
              </div>
            </div>
          </div>

          <!--<div class="carousel-item">
            <div class="carousel-background"><img src="{% static 'cinetic/assets/img/intro-carousel/4.jpg' %}" alt="">
            </div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Nam libero tempore</h2>
                <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed
                quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
                Ut enim ad minima veniam, quis nostrum.</p>
                <a href="#featured-services" class="btn-get-started scrollto">Get Started</a>
              </div>
            </div>
          </div>-->

        </div>

        <!--<a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon ion-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon ion-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>-->

      </div>
    </div>
  </section><!-- #intro -->

    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
     <!-- JavaScript Libraries --> 
    <!--<script src="{% static 'cinetic/assets/lib/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/jquery/jquery-migrate.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/superfish/hoverIntent.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/superfish/superfish.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/lightbox/js/lightbox.min.js' %}"></script>
    <script src="{% static 'cinetic/assets/lib/touchSwipe/jquery.touchSwipe.min.js' %}"></script>-->
     <!-- Template Main Javascript File --> 
    <script src="{% static 'cinetic/assets/js/main.js' %}"></script>  
     <!-- Contact Form JavaScript File --> 
    <script src="contactform/contactform.js"></script>


{% endblock %} 
  

mainsite/cinetic/templates/cinetic/projets.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block section %}


    <section id="portfolio"  class="section-bg" >
      <div class="container" align="center">

        <header class="section-header">
          <h3 class="section-title">{% translate "Mes Projets" %}</h3>
        </header>

        <div class="row">
          <header class="section-header wow fadeInUp">
              <p>{% translate "Sur cette page sont présentés les projets réalisés à ce jour." %}</p>
          </header>

          <table class="styled-table">
            <thead>
              <tr>
                <th>Nom</th>
                <th>Description</th>
                <th>Type</th>
                <th>Github</th>
                <th>Url</th>
                <th>Historique</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>GrandPy</td>
                <td><div class="popup" onclick="showDescription('popup1')">{% translate "Lire" %}<span class="popuptext" id="popup1">
                  {% translate "Il s'agit d'un bot hébergé sur Heroku qui vous affiche la carte du lieu recherché ainsi qu'un extrait de l'histoire de ce lieu." %}<br />
                  {% translate "Les requêtes utilisent Ajax pour communiquer avec le serveur." %}</span>
                  </div>
                </td>
                <td>Flask</td>
                <td><a href="https://github.com/6netic/GrandPy" target="_blank">Dépôt</a></td>
                <td><a href="https://grandpy-ebres.herokuapp.com" target="_blank">Site</a></td>
                <td> - </td>
              </tr>
              <tr>
                <td>PurBeurre</td>
                <td><div class="popup" onclick="showDescription('popup2')">{% translate "Lire" %}<span class="popuptext" id="popup2">
                  {% translate "Site qui propose des produits plus sains que celui que vous entrez." %}<br />
                  {% translate "La base de données alimentaire provient d'OpenFoodFacts via son API." %}<br />
                  {% translate "Vous pouvez créer un compte et sauvegarder vos aliments préférés." %}</span>
                  </div>
                </td>
                <td>Django</td>
                <td><a href="https://github.com/6netic/dixpb" target="_blank">Dépôt</a></td>
                <td><a href="{% url 'purbeurre:index' %}" target="_blank">Site</a></td>
                <td> - </td>
              </tr>
              <tr>
                <td>Shooting Target</td>
                <td><div class="popup" onclick="showDescription('popup3')">{% translate "Lire" %}<span class="popuptext" id="popup3">
                  {% translate "Il s'agit d'une appli hébergée sur Heroku qui propose d'afficher le résultat du nombre de points sur une cible de 10 mètres." %}<br />
                  {% translate "La librairie Opencv est utilisée." %}<br />
                  {% translate "Pour le moment, l'appli est sommaire : ne sont reconnus que 10 trous qui ne se touchent pas." %}<br />
                  {% translate "Des exemples de photos et explications sont disponibles sur le dépot Github." %}</span>
                  </div>
                </td>
                <td>Flask</td>
                <td><a href="https://github.com/6netic/shtarget" target="_blank">Dépôt</a></td>
                <td><a href="https://target-ebres.herokuapp.com/" target="_blank">Site</a></td>
                <td> - </td>
              </tr>
              <tr>
                <td>Réservation Transport</td>
                <td><div class="popup" onclick="showDescription('popup4')">{% translate "Lire" %}<span class="popuptext" id="popup4">
                  {% translate "Il s'agit d'une maquette fonctionnelle pour une entreprise qui souhaitait permettre à ses clients d'enregistrer des réservations afin d'être transportés d'un lieu à un autre." %}</span>
                  </div>
                </td>
                <td>Django</td>
                <td><a href="https://github.com/6netic/limobooking" target="_blank">Dépôt</a></td>
                <td><a href="{% url 'booking:index' %}" target="_blank">Site</a></td>
                <td> - </td>
              </tr>
              <tr>
                <td>LeBanlieuZar</td>
                <td><div class="popup" onclick="showDescription('popup5')">{% translate "Lire" %}<span class="popuptext" id="popup5">
                  {% translate "Il s'agit en fait d'un hack du site LeParisien.fr qui permet d'afficher tous les articles." %}<br />
                  {% translate "L'unique intérêt est d'utiliser la librairie BeautifulSoup pour cet usage." %}<br />
                  {% translate "Le site a depuis mis en place une sécurité digne de ce nom : seuls les articles non protégés sont donc visibles." %}</span>
                  </div>
                </td>
                <td>Flask</td>
                <td><a href="https://github.com/6netic/lebanlieuzar" target="_blank">Dépôt</a></td>
                <td><a href="https://lebanlieuzar.herokuapp.com/" target="_blank">Site</a></td>
                <td> - </td>
              </tr>
              <tr>
                <td>MG Labyrinth</td>
                <td><div class="popup" onclick="showDescription('popup6')">{% translate "Lire" %}<span class="popuptext" id="popup6">
                  {% translate "Application Python de jeu avec Pygame." %}<br />
                  {% translate "Il s'agit d'un jeu de labyrinthe en Python qui utilise la librairie Pygame." %}<br />
                  {% translate "Le personnage est Mac Gyver et le but est de l'aider à trouver la sortie en ayant préalablement ramassé 3 objets." %}<br />
                  {% translate "Autrement, la partie sera perdue." %}<br />
                  {% translate "Pour le faire fonctionner, il faudra télécharger le code à partir du dépot." %}</span>
                  </div>
                </td>
                <td>Appli</td>
                <td><a href="https://github.com/6netic/mg_labyrinth" target="_blank">Dépôt</a></td>
                <td> - </td>
                <td> - </td>
              </tr>
              <tr>
                <td>Scrape4Fun</td>
                <td><div class="popup" onclick="showDescription('popup7')">{% translate "Lire" %}<span class="popuptext" id="popup7">
                  {% translate "Application Python permettant de récupérer tous les livres du site books.toscrape.com et les enregistre dans un fichier .csv" %}<br />
                  {% translate "Sur ce projet, c'est la bibliothèque BeautifulSoup qui a été utilisée." %}</span>
                  </div>
                </td>
                <td>Appli</td>
                <td><a href="https://github.com/6netic/scrape_for_fun" target="_blank">Dépôt</a></td>
                <td> - </td>
                <td> - </td>
              </tr>
              <tr>
                <td>L'Orchidée</td>
                <td><div class="popup" onclick="showDescription('popup8')">{% translate "Lire" %}<span class="popuptext" id="popup8">
                  {% translate "Appli web (dans sa v1) permettant d'importer un planning généré par une appli médicale tierce au format PDF et l'affiche dans un tableau tout en permettant d'ajouter un commentaire sur chacune des lignes." %}<br />
                  {% translate "L'intérêt est de pouvoir le consulter sur smartphone (au lieu de l'imprimer) et ainsi faciliter les tournées quotidiennes des infirmières." %}<br />
                  {% translate "La BDD utilisée est en PostgreSQL." %}</span>
                  </div>
                </td>
                <td>Django</td>
                <td><a href="https://github.com/6netic/orchidee" target="_blank">Dépôt</a></td>
                <td><a href="{% url 'lorchidee:index' %}" target="_blank">Site</a></td>
                <td> - </td>
              </tr>
              <tr>
                <td>ATP Men Ranking</td>
                <td><div class="popup" onclick="showDescription('popup9')">{% translate "Lire" %}<span class="popuptext" id="popup9">
                  {% translate "Appli Python permettant de récupérer le classement et matchs des 100 premiers joueurs de tennis de l'ATP." %}<br />
                  {% translate "C'est la partie 1 d'un projet de Machine Learning permettant de déterminer le vainqueur d'un match." %}<br />
                  {% translate "Son utilité est d'aider à la décision d'un pari sur un joueur." %}</span>
                  </div>
                </td>
                <td>Appli</td>
                <td><a href="https://github.com/6netic/atp_men_players" target="_blank">Dépôt</a></td>
                <td> - </td>
                <td> - </td>
              </tr>
            </tbody>
          </table>

         </div>

      </div>
    </section><!-- #portfolio -->

<script type="text/javascript" src="{% static 'cinetic/assets/js/projetsPopup.js' %}"></script>


{% endblock %}

mainsite/cinetic/templates/cinetic/services.html
{% extends "base.html" %}

{% load static %}

{% block section %}

<section id="about">
  <div class="container">

    <header class="section-header">
      <h3>Les Services</h3>
      <p> </p>
    </header>

    <div class="row about-cols">

      <div class="col-md-4 wow fadeInUp">
        <div class="about-col">
          <div class="img">
            <img src="img/about-mission.jpg" alt="" class="img-fluid">
            <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
          </div>
          <h2 class="title"><a href="#">Sites Web</a></h2>
          <p>Création de sites web en utilisant le framework Django ou Flask</p>
        </div>
      </div>

      <div class="col-md-4 wow fadeInUp" data-wow-delay="0.1s">
        <div class="about-col">
          <div class="img">
            <img src="img/about-plan.jpg" alt="" class="img-fluid">
            <div class="icon"><i class="ion-ios-list-outline"></i></div>
          </div>
          <h2 class="title"><a href="#">Applis mobiles</a></h2>
          <p>Développement d'applications pour smartphones. 
          </p>
        </div>
      </div>

      <div class="col-md-4 wow fadeInUp" data-wow-delay="0.2s">
        <div class="about-col">
          <div class="img">
            <img src="img/about-vision.jpg" alt="" class="img-fluid">
            <div class="icon"><i class="ion-ios-eye-outline"></i></div>
          </div>
          <h2 class="title"><a href="#">Applis Python</a></h2>
          <p>
            Développement d'applications en Python.
          </p>
        </div>
      </div>

    </div>

  </div>
</section>

<section id="services">
  <div class="container">
    <header class="section-header wow fadeInUp">
      <p></p><p></p>
    </header>
  </div>
</section>

{% endblock %}  