mainsite/booking/urls.py
from django.urls import path
from . import views

# Contains paths for 6netic app
app_name = 'booking'

urlpatterns = [
    path('index', views.index, name='index'),
    path('home', views.home, name='home'),
    path('aeroports', views.aeroports, name='aeroports'),
    path('gares', views.gares, name='gares'),
    path('otherDestination', views.otherDestination, name='otherDestination'),
    path('displayJourney/<str:destination>/', views.displayJourney, name='displayJourney'),
    path('selectJourney', views.selectJourney, name='selectJourney'),
    path('recordJourney', views.recordJourney, name='recordJourney'),
    path('cancelJourney', views.cancelJourney, name='cancelJourney'),
]

mainsite/booking/models.py
from django.db import models


class Booking(models.Model):
    """ Database for Bookings app """

    destination = models.CharField('Destination', max_length=250)
    departureDate = models.DateField('Date de départ')
    departureTime = models.CharField('Heure de départ', max_length=5)
    sharing = models.CharField('Partage', max_length=3)
    firstname = models.CharField('Prénom', max_length=250)
    lastname = models.CharField('Nom de famille', max_length=250)
    email = models.EmailField('Email', max_length=70)
    price = models.DecimalField('Prix', max_digits=6, decimal_places=2)

    class Meta:
        managed = True
        db_table = 'booking'
        unique_together = ('destination', 'departureDate', 'email')

mainsite/booking/forms.py
from django import forms


class ReservationForm(forms.Form):
    """ This class creates the form for the reservations """

    destination = forms.CharField(
        label='Destination', max_length=250,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
    )

    departureDate = forms.DateField(
        label='Date de départ:',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'date',
            })
    )

    hoursList = [
        ('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'),
        ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'),
        ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'),
        ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'),
        ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'),
        ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')
    ]
    hour = forms.ChoiceField(
        label='Heure:',
        choices=hoursList,
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            })
    )

    minutesList = [('00', '00'), ('20', '20'), ('40', '40')]
    minute = forms.ChoiceField(
        label='Minutes:',
        choices=minutesList,
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                
            })
    )

    sharingList = [('Oui', 'Oui'), ('Non', 'Non')]
    sharing = forms.ChoiceField(
        label='Partage de course:',
        choices=sharingList,
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            })
    )

    firstname = forms.CharField(
        label='Prénom:',
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'size': '25',
            })
    )

    lastname = forms.CharField(
        label='Nom de famille:',
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'size': '25',
            })
    )

    email = forms.EmailField(
        label='Email:',
        max_length=40,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'size' : '30',
            })
    )


class SearchForm(forms.Form):
    """ This class creates a form to find a booking """

    departureDate = forms.DateField(
        label='Date de départ:',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'date',
            })
    )

    email = forms.EmailField(
        label='Email:',
        max_length=40,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'size' : '30',
            })
    )
        

mainsite/booking/views.py
import os
import dotenv
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.http import Http404
from .viewsCompute import *
from .models import Booking
from .forms import ReservationForm
from .forms import SearchForm


dotenv.load_dotenv(os.path.join('.env'))

def homepage(request):
    """ Homepage of the application """

    home = True
    return render(request, 'cinetic/index.html', locals())


def index(request):
    """ Index of the application, first access to the app """

    return render(request, "booking/index.html")


def home(request):
    """ Homepage of the application """

    return render(request, "booking/home.html")


def aeroports(request):
    """ Homepage of the application """

    return render(request, "booking/aeroports.html")


def gares(request):
    """ Homepage of the application """

    return render(request, "booking/gares.html")


def otherDestination(request):
    """ Homepage of the application """

    googleApiKey = os.getenv("GOOGLE_API_KEY")
    if request.method == 'GET':
        # destination is sent via GET method
        if (request.GET.get("destination")):
            destination = request.GET.get("destination")
            return redirect('booking:displayJourney', destination=destination)
        # This is the first access to autreDestination page
        else:
            form = ReservationForm()
            return render(request, "booking/autredestination.html", locals())


def displayJourney(request, destination):
    """ View for displaying empty form in destinations.html page """

    googleApiKey = os.getenv("GOOGLE_API_KEY")
    # This is the first time we access the page with destination value given
    if request.method == 'GET':
        form = ReservationForm()
        return render(request, "booking/destinations.html", locals())


def selectJourney(request):
    """ Selecting required date and time """

    googleApiKey = os.getenv("GOOGLE_API_KEY")
    # Form is sent with POST method
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            # Retrieving datas from form
            destination = form.cleaned_data['destination']
            departureDate = form.cleaned_data['departureDate']
            hour = form.cleaned_data['hour']
            minute = form.cleaned_data['minute']
            sharing = form.cleaned_data['sharing']
            departureTime = hour + ":" + minute
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']
            email = form.cleaned_data['email']

            dayOfReservation = departureDate.strftime("%a")
            if (dayOfReservation == "Mon" or dayOfReservation == "Tue" or
                dayOfReservation == "Wed" or dayOfReservation == "Thu" or
                    dayOfReservation == "Fri"):
                if (int(hour) >= 8 and int(hour) < 20):
                    tarifKilometre = 1.01
                else:
                    tarifKilometre = 1.56
            if (dayOfReservation == "Sat" or dayOfReservation == "Sun" or
               (departureDate in bankHolidayDates)):
                tarifKilometre = 1.61

            distance = float(request.POST.get("distance")) / 1000
            prixCourse = (tarifKilometre * distance)
            prixCourse = round(prixCourse, 2)
            # Looking for other bookings
            try:
                bookingsInBase = Booking.objects.filter(
                    departureDate__exact=departureDate).filter(
                    sharing__exact=sharing).filter(
                    destination__exact=destination
                )
                if bookingsInBase:
                    bookingList = []
                    pricesDict = {}
                    for booking in bookingsInBase:
                        bookingList.append(booking.departureTime)
                    uniqueBookingList = set(bookingList)
                    for b in uniqueBookingList:
                        if (bookingList.count(b) + 1) <= 3:
                            reductRate = 0.95
                        elif (bookingList.count(b) + 1) > 3 and (bookingList.count(b) + 1) <= 7:
                            reductRate = 0.92
                        elif (bookingList.count(b) + 1) > 7 and (bookingList.count(b) + 1) <= 22:
                            reductRate = 0.84
                        elif (bookingList.count(b) + 1) > 22 and (bookingList.count(b) + 1) <= 54:
                            reductRate = 0.76
                        pricesDict[b] = round(prixCourse * reductRate, 2)
                else:
                    onlyOne = True
            except:
                pass
                # On pourrait faire un retour HTTP 404

            return render(request, "booking/destinations.html", locals())


def recordJourney(request):
    """ Records values in the database """

    if request.method == 'POST':

        # Retrieve first group of variables
        destination = request.POST.get("destination")
        dep = (request.POST.get("departureDate")).split("-")
        departureDate = date(int(dep[2]), int(dep[1]), int(dep[0]))
        departureTime = request.POST.get("departureTime")
        sharing = request.POST.get("sharing")
        lastname = request.POST.get("lastname")
        firstname = request.POST.get("firstname")
        email = request.POST.get("email")
        prixCourse = float(request.POST.get("prixCourse"))
        # Register booking into database
        if request.POST.get("validation"):
            try:
                newBooking = Booking.objects.create(
                    destination=destination,
                    departureDate=departureDate,
                    departureTime=departureTime,
                    sharing=sharing,
                    lastname=lastname,
                    firstname=firstname,
                    email=email,
                    price=prixCourse,
                )
                messageOk = "Réservation enregistrée"
                message = True
                # return render(request, "booking/record.html", locals())
            except:
                messageNok = "Vous avez déjà effectué une réservation à cette date pour cette destination"
                message = True
            return render(request, "booking/record.html", locals())

        return render(request, "booking/record.html", locals())


def cancelJourney(request):
    """ Cancels a booking from the database """

    if request.method == 'GET':
        if request.GET.get("email"):
            email = request.GET.get("email")
            departureDate = request.GET.get("departureDate")
            try:
                cancel = Booking.objects.filter(email__contains=email)\
                                .filter(departureDate=departureDate)
                if cancel:
                    return render(request, "booking/cancel.html", locals())
                else:
                    message = "Aucune réservation trouvée à cette date"
                    return render(request, "booking/cancel.html", locals())
            except:
                pass

        first = True
        form = SearchForm()
        return render(request, "booking/cancel.html", locals())

    if request.method == 'POST':
        id = request.POST.get("id")
        try:
            delete = Booking.objects.filter(pk=id).delete()
            messDel = "La réservation a bien été annulée."
        except:
            pass

        return render(request, "booking/cancel.html", locals())

mainsite/booking/templates/booking/aeroports.html
{% extends 'booking/base.html' %}

{% load static %}

{% block wrapper %}
	<table width="257" border="0" cellpadding="0" cellspacing="0" align="center">
	<tr>
		<td>
			<img src="{% static 'booking/assets/img/aeroports_03.png' %}" width="257" height="75" alt="" align="left">
		</td>
	</tr>
	<tr>
		<td>
			<a href="{% url 'booking:displayJourney' destination='Aéroport de Paris-Orly (ORY), Orly, France' %}">
				<img src="{% static 'booking/assets/img/aeroports_05.png' %}" width="257" height="102" alt="Orly" align="left">
			</a>
		</td>
	</tr>
	<tr>
		<td>
			<a href="{% url 'booking:displayJourney' destination='Aéroport Paris Beauvais, Route de l\'Aéroport, Tillé, France' %}">
				<img src="{% static 'booking/assets/img/aeroports_06.png' %}" width="257" height="112" alt="Beauvais" align="left">
			</a>
		</td>
	</tr>
	<tr>
		<td>
			<a href="{% url 'booking:displayJourney' destination='Aéroport Charles-de-Gaulle (CDG), Roissy-en-France, France' %}">
				<img src="{% static 'booking/assets/img/aeroports_07.png' %}" width="257" height="112" alt="Charles De Gaulle" align="left">
		</td>
	</tr>
	<tr>
		<td>
			<img src="{% static 'booking/assets/img/aeroports_08.png' %}" width="257" height="132" alt="" align="left">
		</td>
	</tr>
	<tr>
		<td>
			<a href="{% url 'booking:home' %}">
				<img src="{% static 'booking/assets/img/aeroports_09.png' %}" width="257" height="80" alt="retour" align="left">
			</a>
		</td>
	</tr>
	<tr>
		<td>	
			<img src="{% static 'booking/assets/img/aeroports_10.png' %}" width="257" height="104" alt="" align="left">
		</td>
	</tr>
</table>

{% endblock %}

mainsite/booking/templates/booking/cancel.html
{% extends 'booking/base.html' %}

{% load static %}

{% block wrapper %}
  <p id="ligne1">Annuler une réservation</p>
  {% if first %}
    <form action="{% url 'booking:cancelJourney' %}" method="GET">
      <table align="center" class="tableau">
  	    <tr>
          <td>{{ form.departureDate.label }} {{ form.departureDate }}</td>
          <td>{{ form.email.label }} {{ form.email }}</td>
          <td valign="bottom"><button class="btn btn-success" type="submit"/>Rechercher</button></td>
        </tr>    	    
      </table>
    </form>
    <br /><br />
  {% endif %} 
  {% if cancel %}
        <div align="center">
      <table class="tableau" width="60%">        
        <form action="{% url 'booking:cancelJourney' %}" method="POST">
        {% csrf_token %}
          {% for c in cancel %}
        <tr>
          <td align="left" colspan="3">Destination: {{ c.destination }}</td>
        </tr>
        <br />
        <tr>
          <td align="left">Date de départ: {{ c.departureDate }}</td>
          <td align="left">Heure de départ: {{ c.departureTime }}</td>
          <td align="left">Nom: {{ c.lastname }}</td>
          <td align="left">Prénom: {{ c.firstname }}</td>
        </tr>
        <tr>
          <input type="hidden" name="id" value="{{ c.id }}">
          <td align="center" colspan="4">
            <button type="submit" class="btn btn-success">Annuler la réservation</button>
          </td>
        </tr>
           {% endfor %}
        </form>
      </table>
      <div>      

  {% elif message %}
    <div>
    	<br />
  	  <table class="tableau" width="60%" align="center">
  	  	<tr>
  	  		<td>Aucune réservation n'a été trouvée à cette date pour cet utilisateur</td>
  	  	</tr>
  		<tr>
  		  <td>
  		  <form>
	    <input type="button" class="button1" value="Page précédente" onclick="history.go(-1)">
	      </form>
	      </td>
	    </tr>
      </table>
    </div>
  {% elif delete %}
    <div>
    	<br />
  	  <table class="tableau" width="60%" align="center">
  	  	<tr>
  	  		<td>La réservation a bien été annulée. Merci de votre confiance.</td>
  	  	</tr>
  		<tr>
  		  <td>
  		  <a href="{% url 'booking:index' %}">
	    <input type="button" class="button1" value="Retour à l'Accueil">
	      </a>
	      </td>
	    </tr>
      </table>
    </div>

  {% endif %}


{% endblock %}

mainsite/booking/templates/booking/destinations.html
{% extends 'booking/base.html' %}

{% load static %}

{% block wrapper %}
	<form action="{% url 'booking:selectJourney' %}" method="POST">
    {% csrf_token %}
  <p id="ligne1">Destination : <span id="destination">{{ destination }}</span></p>
  <p class="ligne2">Distance du trajet : <span id="laDistance"></p>
  <p>
  	<table align="center" class="tableau">
  	  <tr>
        <td>{{ form.lastname.label }} {{ form.lastname }}</td>
        <td>{{ form.firstname.label }} {{ form.firstname }}</td>
        <td>{{ form.email.label }} {{ form.email }}</td>
      </tr>    	    
    </table>
  </p>
  <p>
  	<table align="center" class="tableau">
      <tr>
        <td>{{ form.departureDate.label }} {{ form.departureDate }}</td>
        <td>{{ form.hour.label }} {{ form.hour }}</td>
        <td>{{ form.minute.label }} {{ form.minute }}</td>
        <td>{{ form.sharing.label }} {{ form.sharing }}</td>
        <td valign="bottom"><button type="submit" class="btn btn-success">Afficher le tarif</button></td> 
      </tr>
    </table>
        <!-- Voir s'il est vraiment nécessaire d'inclure ces 2 variables dans POST -->
        <input type="hidden" value="{{ destination }}" name="destination">
        <input type="hidden" id="distance" name="distance" value="">
    </form>
  </p>
  <br><br>
<!-- Si on a pricesDict, c'est qu'on a d'autres réservations à cette date et destination -->
  {% if pricesDict %}
    {% if departureTime in pricesDict.keys %} 
      <div align="center">
      <table class="tableau" width="60%">        
        <form action="{% url 'booking:recordJourney' %}" method="POST">
        {% csrf_token %}
        <tr>
          <td align="left">Heure de départ: {{ departureTime }}</td>
          <td align="right"> Tarif: {{ prixCourse }} euros TTC</td>
          <input type="hidden" name="destination" value="{{ destination }}">
          <input type="hidden" name="departureDate" value="{{ departureDate }}">
          <input type="hidden" name="departureTime" value="{{ key }}">
          <input type="hidden" name="sharing" value="{{ sharing }}">
          <input type="hidden" name="firstname" value="{{ firstname }}">
          <input type="hidden" name="lastname" value="{{ lastname }}">
          <input type="hidden" name="email" value="{{ email }}">
          <input type="hidden" name="prixCourse" value="{{ prixCourse }}">
          <td align="right">
            <button type="submit" class="btn btn-success">Je choisis cet horaire</button>
          </td>
        </tr>
        </form>
      </table>
      <div>      
    {% else %}      
      <div align="center">
      <table class="tableau" width="60%">        
        <form action="{% url 'booking:recordJourney' %}" method="POST">
        {% csrf_token %}
        <tr>
          <td align="left">Heure de départ: {{ departureTime }}</td>
          <td align="right"> Tarif: {{ prixCourse }} euros TTC</td>
          <input type="hidden" name="destination" value="{{ destination }}">
          <input type="hidden" name="departureDate" value="{{ departureDate }}">
          <input type="hidden" name="departureTime" value="{{ departureTime }}">
          <input type="hidden" name="sharing" value="{{ sharing }}">
          <input type="hidden" name="firstname" value="{{ firstname }}">
          <input type="hidden" name="lastname" value="{{ lastname }}">
          <input type="hidden" name="email" value="{{ email }}">
          <input type="hidden" name="prixCourse" value="{{ prixCourse }}">
          <td align="right">
            <button type="submit" class="btn btn-success">Je choisis cet horaire</button>
          </td>
        </tr>
        </form>
      </table>
      <div>      
    {% endif %}
<!-- On affiche les autres tarifs pour le même jour et même destination -->
      <br /><br />
      <div align="center">
        <p style="color:yellow;">Les autres tarifs pour cette destination le même jour:</p>
      </div>
    {% for key, prixCourse in pricesDict.items %}    
      {% if key != departureTime %}
      
      <div align="center">
      <table class="tableau" width="60%">        
        <form action="{% url 'booking:recordJourney' %}" method="POST">
        {% csrf_token %}
        <tr>
          <td align="left">Heure de départ: {{ key }}</td>
          <td align="right"> Tarif: {{ prixCourse }} euros TTC</td>
          <input type="hidden" name="destination" value="{{ destination }}">
          <input type="hidden" name="departureDate" value="{{ departureDate }}">
          <input type="hidden" name="departureTime" value="{{ key }}">
          <input type="hidden" name="sharing" value="{{ sharing }}">
          <input type="hidden" name="firstname" value="{{ firstname }}">
          <input type="hidden" name="lastname" value="{{ lastname }}">
          <input type="hidden" name="email" value="{{ email }}">
          <input type="hidden" name="prixCourse" value="{{ prixCourse }}">
          <td align="right">
            <button type="submit" class="btn btn-success">Je choisis cet horaire</button>
          </td>
        </tr>
        </form>
      </table>
      <div>
      {% endif %}      
    {% endfor %} 

  {% elif onlyOne %} 
    <div align="center">
      <table class="tableau" width="60%">
      <form action="{% url 'booking:recordJourney' %}" method="POST">
      {% csrf_token %}       
        <tr>
          <td align="left">Heure de départ: {{ departureTime }}  </td>
          <td align="right"> Tarif: {{ prixCourse }} euros TTC</td>
          <input type="hidden" name="destination" value="{{ destination }}">
          <input type="hidden" name="departureDate" value="{{ departureDate }}">
          <input type="hidden" name="departureTime" value="{{ departureTime }}">
          <input type="hidden" name="sharing" value="{{ sharing }}">
          <input type="hidden" name="firstname" value="{{ firstname }}">
          <input type="hidden" name="lastname" value="{{ lastname }}">
          <input type="hidden" name="email" value="{{ email }}">
          <input type="hidden" name="prixCourse" value="{{ prixCourse }}">
          <td align="right">
            <button type="submit" class="btn btn-success">Je choisis cet horaire</button>
          </td>
        </tr>
      </form>        
      </table>    
    <div>  

  {% endif %}

<br /><br /><br />

<script src="{% static 'booking/assets/js/get_distance_time.js' %}"></script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key={{ googleApiKey }}&callback=initMap"></script>

{% endblock %}

mainsite/booking/templates/booking/home.html
{% extends "booking/base.html" %}

{% load static %}

{% block wrapper %}
	<table width="257" cellpadding="0" cellspacing="0" align="center">	
		<tr>
			<td>
				<img src="{% static 'booking/assets/img/destinations_03.png' %}" alt="" width="257" height="75" align="left">
			</td>		
		</tr>
		<tr>
			<td>	
				<a href="{% url 'booking:aeroports' %}"><!-- aeroports_route -->
					<img src="{% static 'booking/assets/img/destinations_05.png' %}" alt="aeroports" width="257" height="102" align="left">
				</a>
			</td>
		</tr>
		<tr>
			<td>
				<a href="{% url 'booking:gares' %}"><!-- gares_route -->
					<img src="{% static 'booking/assets/img/destinations_06.png' %}" width="257" height="112" alt="gares" align="left">
				</a>
			</td>
		</tr>
		<tr>
			<td>
				<a href="{% url 'booking:otherDestination' %}"><!-- autre_route -->
					<img src="{% static 'booking/assets/img/destinations_07.png' %}" width="257" height="112" alt="autre" align="left">
				</a>
			</td>
		</tr>
		<tr>
			<td>
				<img src="{% static 'booking/assets/img/destinations_08.png' %}" width="257" height="132" alt="" align="left">
			</td>
		</tr>
		<tr>
			<td>
				<a href="{% url 'booking:index' %}"><!-- booking -->
					<img src="{% static 'booking/assets/img/destinations_09.png' %}" width="257" height="80" alt="retour" align="left">
				</a>
			</td>
		</tr>
		<tr>
			<td>
				<img src="{% static 'booking/assets/img/destinations_10.png' %}" width="257" height="104" alt="" align="left">
			</td>
		</tr>
	</table>
    
{% endblock %}

mainsite/booking/templates/booking/index.html
{% extends "booking/base.html" %}

{% load static %}

{% block wrapper %}
	<div class="formix">
			<p id='ligne1'>Réservations - LimoSquare</p>
	      	<a href="{% url 'booking:home' %}">
	      	<button type="submit" class="noms_Passagers">Réserver une navette</button></a>
	      	<span class="espace"></span>
	      	<a href="{% url 'booking:cancelJourney' %}">
	      	<button type="submit" class="noms_Passagers">Annuler une réservation</button></a>	
	      		<br /><br />
	      	</p>
			<p id='ligne1'>Booking - LimoSquare</p>
			
			<button type="submit" class="noms_Passagers">Book a shuttle</button>
			<span class="espace"></span>
	      	<button type="submit" class="noms_Passagers">Cancel a booking</button>	
	      		<br /><br />
	</div>	
	    
	<p id="affichError2"></p>
{% endblock %}

mainsite/booking/templates/booking/record.html
{% extends 'booking/base.html' %}

{% load static %}

{% block wrapper %}	

<p id="ligne1">Récapitulatif de la réservation</p>

{% if message %}

  <p>
  	<table class="tableau" align="center">
      <tr>
	  	<td class="espace1" align="right">Destination de la course : </td><td></td><td align="left">{{ destination }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Date de départ : </td><td></td><td align="left">{{ departureDate }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Heure du départ : </td><td></td><td align="left">{{ departureTime }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Partage de la course : </td><td></td><td align="left">{{ sharing }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Nom de famille : </td><td></td><td align="left">{{ lastname }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Prénom : </td><td></td><td align="left">{{ firstname }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Adresse email : </td><td></td><td align="left">{{ email }}</td>
	  </tr>
      <tr>
	  	<td class="espace1" align="right">Prix de la course : </td><td></td><td align="left">{{ prixCourse }} euros TTC</td>
	  </tr>
	</table>	
	<br><br>
	{% if messageOk %}
	<div align="center" style="color: white; font-size: 1.5em;" >{{ messageOk }}</div>
	<a href="{% url 'booking:index' %}"><button class="button1">Retour à l'Accueil</button></a>
	{% elif messageNok %}
	<div align="center" style="color: red; font-size: 1.5em;" >{{ messageNok }}</div>
	<form>
	 <input type="button" class="button1" value="Page précédente" onclick="history.go(-2)">	
	</form>
	
	{% endif %}
  </p>

{% else %}

  <p>
    <form action="{% url 'booking:recordJourney' %}" method="POST">
  	{% csrf_token %}
	<table class="tableau" align="center">
	  <tr>
	  	<td class="espace1" align="right">Destination de la course : </td><td></td><td align="left">{{ destination }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Date de départ : </td><td></td><td align="left">{{ departureDate }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Heure du départ : </td><td></td><td align="left">{{ departureTime }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Partage de la course : </td><td></td><td align="left">{{ sharing }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Nom de famille : </td><td></td><td align="left">{{ lastname }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Prénom : </td><td></td><td align="left">{{ firstname }}</td>
	  </tr>
	  <tr>
	  	<td class="espace1" align="right">Adresse email : </td><td></td><td align="left">{{ email }}</td>
	  </tr>
      <tr>
	  	<td class="espace1" align="right">Prix de la course : </td><td></td><td align="left">{{ prixCourse }} euros TTC</td>
	  </tr>
		<input type="hidden" name="destination" value="{{ destination }}">
        <input type="hidden" name="departureDate" value="{{ departureDate }}">
        <input type="hidden" name="departureTime" value="{{ departureTime }}">
        <input type="hidden" name="sharing" value="{{ sharing }}">
        <input type="hidden" name="firstname" value="{{ firstname }}">
        <input type="hidden" name="lastname" value="{{ lastname }}">
        <input type="hidden" name="email" value="{{ email }}">
        <input type="hidden" name="prixCourse" value="{{ prixCourse }}">
        <input type="hidden" name="validation" value="ok">
	  <tr>
	  	<td></td><td></td><td align="right"><button type="submit" class="btn btn-success">Enregistrer ma réservation</button></td>
	  </tr>  
	</table>	
	</form>
	<br><br>
  </p>
{% endif %}

    	
{% endblock %}